### ISSUE TITLE
InvalidProgramException

### ISSUE THREAD

**Issue by pgw00k** [SrejonKhan/AnotherFileBrowser#10]
In Unity 2023.2.10f1,player setting **API Compatibility Level** is NET Standard and NET Framework,and use packages will throw error:
```
InvalidProgramException: Invalid IL code in (wrapper managed-to-native) Ookii.Dialogs.WinForms.Interop.IFileDialog:Advise (intptr,Ookii.Dialogs.WinForms.Interop.IFileDialogEvents,uint&): IL_0025: ldloc
```

**Comment by shiena** [comment]
It's a bug in Unity. same as https://github.com/gkngkc/UnityStandaloneFileBrowser/issues/135#issuecomment-1914211970

**Comment by shiena** [comment]
Fixed in https://github.com/Unity-Technologies/mono/pull/2003

**Comment by pgw00k** [comment]
Thank you!You are my hero!

**Comment by shiena** [comment]
@pgw00k Please note that the corrected version has not been released or imported, so the error may not be resolved yet.

**Comment by shiena** [comment]
Fixed in Unity2023.2.20 and Unity6000.0.0b15.
