### ISSUE TITLE
Not working in Unity 2023

### ISSUE THREAD

**Issue by Zetan9565** [SrejonKhan/AnotherFileBrowser#12]
OpenFileBrowser() method reports an error says something like 'InvalidProgramException: Invalid IL code in (wrapper managed-to-native) Ookii.Dialogs.WinForms.Interop.IFileDialog:Advise (intptr,Ookii.Dialogs.WinForms.Interop.IFileDialogEvents,uint&): IL_0025: ldloc     65535
'
![image](https://github.com/SrejonKhan/AnotherFileBrowser/assets/40599282/28abf1b2-8bc1-4ead-9c8c-e09f5e7f62c2)

**Comment by SrejonKhan** [comment]
Hello, please refer to #10.
