### ISSUE TITLE
An issue when using SaveFilePanel with defaultFileName

### ISSUE THREAD

**Issue by Mailfth** [SrejonKhan/AnotherFileBrowser#5]
There is a mistake in your code inside the function SaveFilePanel that makes the string defaultFileName make no difference. In your code the function overwrites the defaultFileName and doesn't include it in the default path. Here's how the code should look like (line 90 in my edited code):

![What the function should look like](https://user-images.githubusercontent.com/123246256/213867029-3fc92233-12c8-4133-9790-19dedd59e671.png)

Still, you made a great tool and thank you for that.

**Comment by SrejonKhan** [comment]
Hello, 

Thanks for finding it out. You can open a pull request if you would like to. I would be happy to merge your change.

**Comment by SrejonKhan** [comment]
fixed #6. Thanks for your contribution.
